= Introducing the New bGC(2) Site
:hp-image: https://lh3.googleusercontent.com/KPzSutUvsP8_V3A7F5eP-BB7dYAWpKyKfBHXiwRH8ntQaMKrjqWewXAjW-riM93n1xtJOGyiQR4Ssqg3diLg2WtA_sI3mvn4DvyujVVz1-WcpD-7IVN8h9PiXrzan4APp1UCLFPdFSAOXPY5qBazcs5usUu-zoTInnXabMCdauOyFWXxUPTiyrezGXenOVF77gmSmQg5ExazzfSU5o752bphlZVfzks34SNvwV71EeWnrrfaf9h20PatUd7uQKuPOcAkHFDwRFEqn1_mLJgdDHAm57Hcb8-1P4CZbB-3XZ1jHpuLllxs-uMrPWtkRB-KgQ6Y-1iTwTbqvMVYkC2wtsLfozj2nuEH-UCUTMhT4olwVXeznlpq11alw_Wf0MmVCzWJ9ILy73WlQCwHYEKwA0UB0D6GrxaP-5n5fSyMGVGyryNTIlSXv5y_E8hOOs6NaFnr5DLXJPDOH1NwsaMPeAzMdGVAs1OIizUyg2PnQ5B5b7lEGS_MTL8P0GSKk0F6D__XAmCRfqJANZAUj_v98rRRouPyaiGJuh3RpvYKPipvQEhnmqweQtOMxLeLiZyUJMSx=w1017-h510-no
:hp-tags: blackGirlsCode, web design, Bootsrap

=== I am pleased to announce the redesign of the link:blackgirlscode.github.io[GC(2)] site!  
This is something long overdue and I am very excited about it's development.  It is almost night and day to the previous version and it is a testament of my growth as a developer.  When I first took on this project, it took about three weeks and riddled with errors.  I kept seeing this "clearfix" class thrown about and had no clue as to it's purpose; so I just deleted it.  (Happy to say now I know whats it's for.)  Plus, I used a template that was poor in design and poorly documented.

Features are included that, before, I did not have the know-how to complete. Simple things like an image carousel, a fixed/collapsed navigation bar, some cool transitions, member profiles and testimonials, etc.   

.An Actual Testimonial
image::https://lh3.googleusercontent.com/QVy3lLsG7j-xdR4hN3TZ7RosFmd1Nw-rfEpuelPR19kpZClM6lBc1ZHT4LnqLc8xxBWWSg7mA_UXo3Mf7ZllAau4kJUJPc00Ymo7S3YiWCxPRQmRyLnicqEw93HGGptcNwjoTExTy-sUKAmSE37PJ9134pLYyO24oQSl9JRTmDuCkx6tN8YBvcWZ0yct0h7vxAIw9NxdwlUFfi35Sj7hpx32GKNA5gtRjK7ZvEh2bwC4YGKPRMuEhIleRKX082PQutz7hvVSrGNAgC8bT4ODVlWf0ipedYjq_9IVWj-moWqK0H6rej4kXFsBTYF3SDOSMWAqMpGVhUFXKelvdxNR9TFwyek9V3d0RoS9KCHdwR-x-ijaVzlrDktPD_6osWXuhI6O68N2Kd3EYcdNM0YVWiP0mqHZaStsy6epBm4lYzC5pkQ2Swvtl5B3nc0XGJXOHdn1C88h8iT31tXy6qt508PPlZRH-F_8xhc95TPRw21mUy89t55dryreXIV35uSrTNQa9sfZ_ET6EwXYjov3wEx9mzjOG4-NVeCZNzXYN417sumZjpV-yyutTt6AunpOkYJn=w551-h599-no[Testimonial]


Using Bootstrap was used to build, as well as a few jQuery Plugins.  I'm of the opinion both are used excessively when a simple HTML boilerplate and Vanilla Javascript would suffice, but because of the big picture goals for the organization, they are a good fit.

There still are things I'd like to add such as a schedule of events and the curriculum section for members, but at least for now it is not such an e̶m̶b̶a̶r̶r̶a̶s̶m̶e̶n̶t̶ eye-sore. 

More to come on this, but so far, so good!